language: generic

###############################################################################
before_install:
  - echo "$PATH";
  - travis_retry wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu
  - chmod +x ./install-tl-ubuntu
  - sudo ./install-tl-ubuntu
  - echo "$PATH";
  - export PATH="$PATH";
  - hash -r

###############################################################################
script:
  - pdflatex -halt-on-error -interaction nonstopmode cv.tex
