language: generic

###############################################################################
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y texlive-full

###############################################################################
script:
  - pdflatex -halt-on-error -interaction nonstopmode cv.tex
